#!/bin/sh

# Create the mesh
blockMesh

# create the intial time folder
cp -r 0_org 0

# Write the mesh in folder 0/
postProcess -func writeCellCentres -time 0
ln -s Cx 0/ccx
ln -s Cy 0/ccy
ln -s Cz 0/ccz
# Run sedFoam
sedFoam_rbghMULES > log
