#!/bin/sh

mkdir 1d_profil
python3 -c "import fluidfoam; fluidfoam.create1dprofil('initial_1D_profile/1DSedim/', '.', '40', 'Y', ['alpha.a'])"

# create the intial time folder
blockMesh
cp -r 0_org 0

topoSet -dict system/topoSetDictR2 

funkySetFields -time 0


# Select cellSets for the different zones
topoSet
setFields

# Decompose the case in order to run in parallel 
decomposePar

# Run sedFoam
#mpirun -np 12  overSedDymFoam_rbgh  -parallel > log&
#overSedDymFoam_rbgh  > log&

