#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

#- Run serial
#runApplication $(getApplication)

#- Run parallel
runApplication decomposePar -cellDist
runParallel $(getApplication)
runApplication reconstructPar

runApplication postChannel

#------------------------------------------------------------------------------
