#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------
set -x

TurbulenceModels/Allwclean $*
solver/Allwclean $*
solverMULES/Allwclean $*

#------------------------------------------------------------------------------
