Foam::SinclairJacksonRadial Class Reference
#include <SinclairJacksonRadial.H>
Public Member Functions
TypeName ("SinclairJackson")
SinclairJacksonRadial (const dictionary &dict)
virtual ~SinclairJacksonRadial ()
tmp< volScalarField > g0 (const volScalarField &alpha, const dimensionedScalar &alphaMax) const
tmp< volScalarField > g0prime (const volScalarField &alpha, const dimensionedScalar &alphaMax) const
Public Member Functions inherited from Foam::radialModel
TypeName ("radialModel")
declareRunTimeSelectionTable (autoPtr, radialModel, dictionary,(const dictionary &dict),(dict))
radialModel (const dictionary &dict)
virtual ~radialModel ()
Additional Inherited Members
Static Public Member Functions inherited from Foam::radialModel
static autoPtr< radialModel > New (const dictionary &dict)
Protected Attributes inherited from Foam::radialModel
const dictionary & dict_
Detailed Description
Definition at line 48 of file SinclairJacksonRadial.H.
Constructor & Destructor Documentation
Foam::SinclairJacksonRadial::SinclairJacksonRadial (const dictionary & dict)
Definition at line 46 of file SinclairJacksonRadial.C.
Foam::SinclairJacksonRadial::~SinclairJacksonRadial () virtual
Definition at line 54 of file SinclairJacksonRadial.C.
References g0().
Member Function Documentation
Foam::SinclairJacksonRadial::TypeName ("SinclairJackson")
Foam::tmp< Foam::volScalarField > Foam::SinclairJacksonRadial::g0 (const volScalarField & alpha, const dimensionedScalar & alphaMax) const virtual
Implements Foam::radialModel.
Definition at line 61 of file SinclairJacksonRadial.C.
References g0prime().
Referenced by ~SinclairJacksonRadial().
Foam::tmp< Foam::volScalarField > Foam::SinclairJacksonRadial::g0prime (const volScalarField & alpha, const dimensionedScalar & alphaMax) const virtual
Implements Foam::radialModel.
Definition at line 71 of file SinclairJacksonRadial.C.
Referenced by g0().
The documentation for this class was generated from the following files:
SinclairJacksonRadial.H
SinclairJacksonRadial.C