Foam::LunPressure Class Reference
#include <LunPressure.H>
Public Member Functions
TypeName ("Lun")
LunPressure (const dictionary &dict)
virtual ~LunPressure ()
tmp< volScalarField > granularPressureCoeff (const volScalarField &alpha, const volScalarField &g0, const dimensionedScalar &rhoa, const dimensionedScalar &e) const
tmp< volScalarField > granularPressureCoeffPrime (const volScalarField &alpha, const volScalarField &g0, const volScalarField &g0prime, const dimensionedScalar &rhoa, const dimensionedScalar &e) const
Public Member Functions inherited from Foam::granularPressureModel
TypeName ("granularPressureModel")
declareRunTimeSelectionTable (autoPtr, granularPressureModel, dictionary,(const dictionary &dict),(dict))
granularPressureModel (const dictionary &dict)
virtual ~granularPressureModel ()
Additional Inherited Members
Static Public Member Functions inherited from Foam::granularPressureModel
static autoPtr< granularPressureModel > New (const dictionary &dict)
Protected Attributes inherited from Foam::granularPressureModel
const dictionary & dict_
Detailed Description
Definition at line 48 of file LunPressure.H.
Constructor & Destructor Documentation
Foam::LunPressure::LunPressure (const dictionary & dict)
Definition at line 46 of file LunPressure.C.
Foam::LunPressure::~LunPressure () virtual
Definition at line 54 of file LunPressure.C.
References granularPressureCoeff().
Member Function Documentation
Foam::LunPressure::TypeName ("Lun")
Foam::tmp< Foam::volScalarField > Foam::LunPressure::granularPressureCoeff (const volScalarField & alpha, const volScalarField & g0, const dimensionedScalar & rhoa, const dimensionedScalar & e) const virtual
Implements Foam::granularPressureModel.
Definition at line 61 of file LunPressure.C.
References granularPressureCoeffPrime().
Referenced by ~LunPressure().
Foam::tmp< Foam::volScalarField > Foam::LunPressure::granularPressureCoeffPrime (const volScalarField & alpha, const volScalarField & g0, const volScalarField & g0prime, const dimensionedScalar & rhoa, const dimensionedScalar & e) const virtual
Implements Foam::granularPressureModel.
Definition at line 74 of file LunPressure.C.
Referenced by granularPressureCoeff().
The documentation for this class was generated from the following files:
LunPressure.H
LunPressure.C