Foam::SrivastavaSundaresanFrictionalStress Class Reference
#include <SrivastavaSundaresanFrictionalStress.H>
Public Member Functions
TypeName ("SrivastavaSundaresan")
SrivastavaSundaresanFrictionalStress (const dictionary &dict)
virtual ~SrivastavaSundaresanFrictionalStress ()
virtual tmp< volScalarField > frictionalPressure (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const dimensionedScalar &Fr, const dimensionedScalar &eta, const dimensionedScalar &p) const
virtual tmp< volScalarField > frictionalPressurePrime (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const dimensionedScalar &Fr, const dimensionedScalar &eta, const dimensionedScalar &p) const
virtual tmp< volScalarField > muf (const volScalarField &alpha, const volScalarField &Theta, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D, const dimensionedScalar &phi) const
Public Member Functions inherited from Foam::frictionalStressModel
TypeName ("frictionalStressModel")
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
virtual ~frictionalStressModel ()
Additional Inherited Members
Static Public Member Functions inherited from Foam::frictionalStressModel
static autoPtr< frictionalStressModel > New (const dictionary &dict)
Protected Attributes inherited from Foam::frictionalStressModel
const dictionary & dict_
Detailed Description
Definition at line 48 of file SrivastavaSundaresanFrictionalStress.H.
Constructor & Destructor Documentation
Foam::SrivastavaSundaresanFrictionalStress::SrivastavaSundaresanFrictionalStress (const dictionary & dict)
Definition at line 47 of file SrivastavaSundaresanFrictionalStress.C.
References ~SrivastavaSundaresanFrictionalStress().
Foam::SrivastavaSundaresanFrictionalStress::~SrivastavaSundaresanFrictionalStress () virtual
Definition at line 58 of file SrivastavaSundaresanFrictionalStress.C.
References frictionalPressure().
Referenced by SrivastavaSundaresanFrictionalStress().
Member Function Documentation
Foam::SrivastavaSundaresanFrictionalStress::TypeName ("SrivastavaSundaresan")
Foam::tmp< Foam::volScalarField > Foam::SrivastavaSundaresanFrictionalStress::frictionalPressure (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const dimensionedScalar & Fr, const dimensionedScalar & eta, const dimensionedScalar & p) const virtual
Implements Foam::frictionalStressModel.
Definition at line 66 of file SrivastavaSundaresanFrictionalStress.C.
References frictionalPressurePrime().
Referenced by ~SrivastavaSundaresanFrictionalStress().
Foam::tmp< Foam::volScalarField > Foam::SrivastavaSundaresanFrictionalStress::frictionalPressurePrime (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const dimensionedScalar & Fr, const dimensionedScalar & eta, const dimensionedScalar & p) const virtual
Implements Foam::frictionalStressModel.
Definition at line 82 of file SrivastavaSundaresanFrictionalStress.C.
References muf().
Referenced by frictionalPressure().
Foam::tmp< Foam::volScalarField > Foam::SrivastavaSundaresanFrictionalStress::muf (const volScalarField & alpha, const volScalarField & Theta, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D, const dimensionedScalar & phi) const virtual
Implements Foam::frictionalStressModel.
Definition at line 99 of file SrivastavaSundaresanFrictionalStress.C.
Referenced by frictionalPressurePrime().
The documentation for this class was generated from the following files:
SrivastavaSundaresanFrictionalStress.H
SrivastavaSundaresanFrictionalStress.C