Foam::SchaefferFrictionalStress Class Reference
#include <SchaefferFrictionalStress.H>
Public Member Functions
TypeName ("Schaeffer")
SchaefferFrictionalStress (const dictionary &dict)
virtual ~SchaefferFrictionalStress ()
virtual tmp< volScalarField > frictionalPressure (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const dimensionedScalar &Fr, const dimensionedScalar &eta, const dimensionedScalar &p) const
virtual tmp< volScalarField > frictionalPressurePrime (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const dimensionedScalar &Fr, const dimensionedScalar &n, const dimensionedScalar &p) const
virtual tmp< volScalarField > muf (const volScalarField &alpha, const volScalarField &Theta, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D, const dimensionedScalar &phi) const
Public Member Functions inherited from Foam::frictionalStressModel
TypeName ("frictionalStressModel")
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
virtual ~frictionalStressModel ()
Additional Inherited Members
Static Public Member Functions inherited from Foam::frictionalStressModel
static autoPtr< frictionalStressModel > New (const dictionary &dict)
Protected Attributes inherited from Foam::frictionalStressModel
const dictionary & dict_
Detailed Description
Definition at line 48 of file SchaefferFrictionalStress.H.
Constructor & Destructor Documentation
Foam::SchaefferFrictionalStress::SchaefferFrictionalStress (const dictionary & dict)
Definition at line 47 of file SchaefferFrictionalStress.C.
Foam::SchaefferFrictionalStress::~SchaefferFrictionalStress () virtual
Definition at line 57 of file SchaefferFrictionalStress.C.
References frictionalPressure().
Member Function Documentation
Foam::SchaefferFrictionalStress::TypeName ("Schaeffer")
Foam::tmp< Foam::volScalarField > Foam::SchaefferFrictionalStress::frictionalPressure (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const dimensionedScalar & Fr, const dimensionedScalar & eta, const dimensionedScalar & p) const virtual
Implements Foam::frictionalStressModel.
Definition at line 65 of file SchaefferFrictionalStress.C.
References frictionalPressurePrime().
Referenced by ~SchaefferFrictionalStress().
Foam::tmp< Foam::volScalarField > Foam::SchaefferFrictionalStress::frictionalPressurePrime (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const dimensionedScalar & Fr, const dimensionedScalar & n, const dimensionedScalar & p) const virtual
Implements Foam::frictionalStressModel.
Definition at line 81 of file SchaefferFrictionalStress.C.
References muf().
Referenced by frictionalPressure().
Foam::tmp< Foam::volScalarField > Foam::SchaefferFrictionalStress::muf (const volScalarField & alpha, const volScalarField & Theta, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D, const dimensionedScalar & phi) const virtual
Implements Foam::frictionalStressModel.
Definition at line 96 of file SchaefferFrictionalStress.C.
Referenced by frictionalPressurePrime().
The documentation for this class was generated from the following files:
SchaefferFrictionalStress.H
SchaefferFrictionalStress.C