#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm -time 0: -withZero

# Remove logs
rm -rf  gradPOSC.txt log*

# replace forceProperties and controlDict files
cp constant/forceProperties.sedim constant/forceProperties
cp system/controlDict.sedim system/controlDict

