#!/bin/bash
#OAR -n DraggingPlate_CoarseLong_guillard_U0.05_KEpsilon
#OAR -l /nodes=1/core=1,walltime=24:00:00
#OAR --stdout log.out
#OAR --stderr errors.err

source /etc/profile
module load openfoam/2206plus
export OMPI_MCA_plm_rsh_agent=oar-envsh

# Nombre de processus parallèles
NBCPUS=$(cat ${OAR_NODEFILE} | wc -l)


# Lancement
overSedDymFoam_rbgh
#mpirun -np ${NBCPUS} -machinefile  ${OAR_NODEFILE} overSedDymFoam_rbgh -parallel 
