#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------
set -x

wclean

cd ../solver
wclean libso phaseModel
wclean libso ppModel
wclean libso interfacialModels
wclean libso kineticTheoryModels
wclean libso granularRheologyModels

#------------------------------------------------------------------------------
