#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean

cd ../solver
wclean libso phaseModel
wclean libso ppModel
wclean libso interfacialModels
wclean libso kineticTheoryModels
wclean libso granularRheologyModels

# ----------------------------------------------------------------- end-of-file
