#!/bin/sh

# create the mesh
foamCleanPolyMesh
blockMesh
sed -i -e 's/empty/emptyy/g' constant/polyMesh/boundary
snappyHexMesh -overwrite
sed -i -e 's/emptyy/empty/g' constant/polyMesh/boundary
extrudeMesh

# create the intial time folder
cp -r 0_org 0

# Decompose the case in order to run in parallel (on 16 cores)
decomposePar

# Run sedFoam in parallel
mpirun -np 16 sedFoam_rbgh -parallel > log&
