#!/bin/sh

# create the intial time folder
blockMesh
cp -r 0_org 0

# Select cellSets for the different zones
topoSet
setFields

# Decompose the case in order to run in parallel (on 8 cores)
decomposePar

# Run sedFoam
mpirun -np 8  overSedDymFoam_rbgh  -parallel > log.out&

