#!/bin/sh
# create the mesh
blockMesh

# create the intial time folder
cp -r 0_org 0

## initialise alpha field
setFields

# Decompose the case in order to run in parallel (on 4 cores)
decomposePar

# Run sedFoam in parallel
mpirun -np 4 sedFoam -parallel > log 2> err &
