#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

umask 22
rm -rf html latex man
doxygen --version
doxygen
cp twitter.png html/.
cp github.png html/.
# fix permissions (NB: '+X' and not '+x'!)
chmod -R a+rX ./

# ----------------------------------------------------------------- end-of-file
