#!/bin/bash
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------

module load python/3.8.2
set -x

umask 22
rm -rf mcssout html latex man
pip install -U jinja2 Pygments
#git clone git://github.com/mosra/m.css
git clone https://github.com/mosra/m.css.git
cd m.css/documentation
cp ../../doxygen.py .
python3 doxygen.py ../../conf.py
cd ../..
cp images/* mcssout/html/.
# fix permissions (NB: '+X' and not '+x'!)
chmod -R a+rX ./

#------------------------------------------------------------------------------
