#!/bin/sh

# create the intial time folder
blockMesh
cp -r 0_org 0

topoSet -dict system/topoSetDictR2 

refineMesh -dict system/refineMeshDict2 -overwrite

# Add the cylinder mesh
mergeMeshes . ../sphereMesh -overwrite


# Select cellSets for the different zones
topoSet
setFields


# Decompose the case in order to run in parallel (on 4 cores)
decomposePar
# Run sedFoam
#mpirun -np 4 sedFoam_DriftDyM -parallel > log&
#mpirun -np 4 overPimpleDyMFoam -parallel > log&
#mpirun -np 2  overSedDymFoam_rbgh  -parallel > log&
#overSedDymFoam_rbgh  > log&

