#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

turbulenceModels/Allwmake

wilcoxomegawallfunction/Allwmake

# ----------------------------------------------------------------- end-of-file
