#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------
set -x

turbulenceModels/Allwmake

if [ -f wallFunctions/Allwmake ]
then
    wallFunctions/Allwmake
else
    echo "Missing: wallFunctions/Allwmake"
fi

#------------------------------------------------------------------------------
