#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso turbulenceModels
wclean libso libmyturbulenceModels

# ----------------------------------------------------------------- end-of-file
