#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm

# Remove postProcessing
rm -rf postProcessing

# Remove processor directories
rm -rf  processor* dynamicCode

# Remove logs
rm  gradPOSC.txt log
