#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm

# Remove netCDF file
rm -f postProcessing/*.nc

# Remove processor directories
rm -rf  processor* dynamicCode

# Remove logs
rm  gradPOSC.txt log
