#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm -time 0: -withZero

# Remove processors directories
rm -r processor*

# Remove dynamicCode
rm -r dynamicCode

# Remove postProcessing
rm -r postProcessing/*

# Remove mesh information in constant
rm constant/C*

# Remove logs
rm  gradPOSC.txt log
