#!/bin/sh

# create the mesh
foamCleanPolyMesh
blockMesh

# Decompose the case in order to run in parallel (on 16 cores)
decomposePar

# Run sedFoam in parallel
mpirun -np 16 sedFoam_rbgh -parallel > log&
