#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso granularRheologyModels
wclean libso phaseModel
wclean libso ppModel
wclean libso interfacialModels
wclean libso kineticTheoryModels
wclean

# ----------------------------------------------------------------- end-of-file
