#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm -time 0: -withZero

rm -rf OAR.*
# Remove processor directories
rm -rf  processor*

# Remove logs
rm  gradPOSC.txt log

