#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm -time 0: -withZero

# Remove processor directories
rm -rf  processor* dynamicCode

# Remove logs
rm  gradPOSC.txt log
