#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

(cd sphereAndBackground && mpirun -np 4 overSedDymFoam_rbgh -parallel > log.out&)

#------------------------------------------------------------------------------

